ENV['RCT_NEW_ARCH_ENABLED'] = '0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, "15.1"

install! 'cocoapods', :deterministic_uuids => false

target 'PATHWAY' do
  use_react_native!(:path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native',
      :mac_catalyst_enabled => false
    )
  end
end
