ENV['RCT_NEW_ARCH_ENABLED'] = '0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

target 'PATHWAY' do
  # --- MANUAL LINKING (VERIFIED) ---
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  
  # The fixed names based on your 'ls' output:
  pod 'HtmlToPdf', :path => '../node_modules/react-native-html-to-pdf'
  pod 'react-native-print', :path => '../node_modules/react-native-print'
  # ---------------------------------

  use_react_native!(:path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native',
      :mac_catalyst_enabled => false
    )
  end
end